<?php

namespace AppBundle\Repository;

/**
 * GeographieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeographieRepository extends \Doctrine\ORM\EntityRepository
{





}
