<?php

namespace AppBundle\Repository;

/**
 * ObservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservationRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * Find last 10 validated observations
	 *
	 * @param int $firstResult The first result returned (important for paging)
	 * @param int $maxResults The maximum results returned
	 * @param bool $validation The validation status
	 * 
	 * Return array of Observation objects
	 */
	public function findObservations($firsResult, $maxResults, $validation)
	{
		$qb = $this->createQueryBuilder('observation');

		$qb->where('observation.valide = :valide')
		   		->setParameter('valide', $validation)
		   ->orderBy('observation.id', 'DESC')
		   ->setFirstResult($firsResult)
		   ->setMaxResults($maxResults)
		;

		return $qb
			->getQuery()
			->getResult()
		;
	}
}
