# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext
    UserBundle\Entity\User: plaintext

  role_hierarchy:
    ROLE_ADMIN:       ROLE_PARTICULIER
    ROLE_SUPER_ADMIN: [ROLE_PARTICULIER, ROLE_NATURALISTE, ROLE_ALLOWED_TO_SWITCH]

  providers:
    main:
      entity:
        class:    UserBundle\Entity\User
        property: username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      pattern:      ^/
      anonymous:    true
      provider:     main
      form_login:
        login_path: login
        check_path: login_check

      logout:
        path: logout
        target: NAO_home

  access_control:
        - { path: ^/back, roles: ROLE_NATURALISTE }
