# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext

  role_hierarchy:
    ROLE_ADMIN:       ROLE_PARTICULIER
    ROLE_SUPER_ADMIN: [ROLE_PARTICULIER, ROLE_NATURALISTE, ROLE_ALLOWED_TO_SWITCH]

  providers:
    in_memory:
      memory:
        users:
          user:  { password: userpass, roles: [ 'ROLE_PARTICULIER' ] }
          admin: { password: adminpass, roles: [ 'ROLE_NATURALISTE' ] }

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      pattern:      ^/
      anonymous:    true
      form_login:
        login_path: login
        check_path: login_check

      logout:
        path: logout
        target: NAO_home

  access_control:
        - { path: ^/back, roles: ROLE_NATURALISTE }
