#Pages du Bundle App
NAO_home:
    path:      /
    defaults:
        _controller: AppBundle:Default:index
    methods:  [GET, POST]

NAO_about:
    path:     /about
    defaults:
        _controller: AppBundle:Default:about
    methods:  [GET, POST]

NAO_contact:
    path:     /contact
    defaults:
        _controller: AppBundle:Default:contact
    methods:  [GET, POST]

NAO_mentions:
    path:     /mentions
    defaults:
        _controller: AppBundle:Default:mentions
    methods:  [GET, POST]

NAO_conditions:
    path:     /conditions
    defaults:
        _controller: AppBundle:Default:conditions
    methods:  [GET, POST]

#Pages Observation

NAO_listObservation:
    path:      /observation/liste
    defaults:
        _controller: AppBundle:Observation:list
    methods:  [GET, POST]

NAO_addObservation:
    path:      /observation/add
    defaults:
        _controller: AppBundle:Observation:add
    methods:  [GET, POST]

# Pages Taxref
NAO_searchEspece:
    path:     /searchEspece
    defaults:
        _controller: AppBundle:Taxref:index
    methods:  [GET, POST]

#Pages Back-Office
NAO_back:
    path:      /back
    defaults:
        _controller: BackOfficeBundle:Back:index
    methods:  [GET, POST]
