#src/Louvre/BilletterieBundle/Ressources/config/routing.yml
NAO_home:
    path:      /
    defaults:
        _controller: AppBundle:Default:index
    methods:  [GET, POST]

NAO_back:
    path:      /back
    defaults:
        _controller: AppBundle:Default:back
    methods:  [GET, POST]

NAO_addObservation:
    path:      /observation/add
    defaults:
        _controller: AppBundle:Default:addOvservation
    methods:  [GET, POST]

login:
    path: /login
    defaults:
        _controller: AppBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout

