NAO_back_office_observations_list:
    path:     /observations/{page}
    defaults:
        _controller: BackOfficeBundle:Back:observationsList
        page: 1
    requirements:
        page: \d+

NAO_back_office_validation_list:
    path:     /validation-list/{page}
    defaults:
        _controller: BackOfficeBundle:Back:validationList
        page: 1
    requirements:
        page: \d+

NAO_back_office_validation:
    path:     /validation/{id}
    defaults:
        _controller: BackOfficeBundle:Moderation:validate

NAO_back_office_deletion:
    path:     /deletion/{page}/{id}
    defaults:
        _controller: BackOfficeBundle:Moderation:delete
